### PR TITLE
Add OS to Click

### PR DESCRIPTION
**Pull request by tsujigiri**

### CODE REVIEW

**Comment by dziemba** [comment]
Do we need this? We don't have it for conversions and we can still parse the raw UserAgent ourselves.

**Comment by tsujigiri** [comment]
It already conveniently categorizes them. We don't use it? E.g. for the fraud tool?

**Comment by dziemba** [comment]
The fraud tool parses the UAs directly in the ruby code. It's nicer to use and we don't have to rely on CAKE providing accuare/up-to-date information.

**Comment by tsujigiri** [comment]
Alright.

**Pull request closed without merging**
